[env]
PACKAGE_ID = "0x139eb7c2155eb3eb74f43215c53c12a1565e99e2"

[tasks."install:devnet"]
script = """
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch devnet sui
"""

[tasks."build:move"]
script = '''
sui move build
'''

[tasks."publish:move"]
dependencies = [
    "build:move",
]
script = '''
sui client publish --gas-budget 30000 --json
'''

[tasks."switch:testnet"]
script = '''
sui client new-env --alias testnet --rpc https://fullnode.testnet.sui.io:443
sui client switch --env testnet
'''

[tasks."install:testnet"]
script = '''
cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui
'''

[tasks."create_wasabi"]
script = '''
sui client call \
    --package ${PACKAGE_ID} \
    --module wasabi \
    --function create_wasabi \
    --gas-budget 1000 \
'''

[tasks."push_wasabi"]
script = '''
sui client call \
    --package ${PACKAGE_ID} \
    --module wasabi \
    --function push_wasabi \
    --args \
        0x0f95f6e1501eb27581c02a6edaed2151068f62b8 \
        114514 \
    --gas-budget 1000 \
'''